apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volume.name }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.volume.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path:  {{ .Values.volume.mountPath }}
