apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.persistentVolumeClaim.claimName }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage:  {{ .Values.volume.storage }}