name: Deploy Specs to Pages

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository ✨ (non-dependabot)
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: actions/checkout@v3

      - name: Check out repository 🎉 (dependabot)
        if: ${{ github.actor == 'dependabot[bot]' }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup node env 📦
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          check-latest: true
          cache: 'npm'

      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1.1.6
        with:
          output: dist
          spec-file: specs/openapi.yaml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
